_target_: hfm.backbones.dit.make_molecular_DiT
name: dit_mf
num_layers: 6
num_heads: 8
num_features_head: 32
cutoff: ${globals.cutoff}
scale_pos: 1.0
scale_mom: 1.0
force_as_grad: false
use_mass_cond: true
use_velocity_cond: true
velocities_embed_encode_magnitude: true
velocities_embed_num_basis: 8
velocities_embed_max_value: 1.55
use_adaptive_layernorm: true
use_task_specific_adaln: true
embed_masses: false
embed_velocities_absolute: false
embed_velocities_relative: false
