_target_: hfm.datasets.fane_datamodule.FANEDataModule
name: fane_ethanol
file_path_train: ../data/fane/ethanol/10k/train/nequip_npz.npz
file_path_val: ../data/fane/ethanol/10k/val/nequip_npz.npz
file_path_test: ../data/fane/ethanol/10k/test/nequip_npz.npz
energy_normalization: mean